[build]
  command = 'npm run build'
  publish = 'public'

[template]
  incoming-hooks = ["Uniform"]

[template.environment]
  CONTENTFUL_SPACE_ID = 'Contentful Space ID'
  CONTENTFUL_ENVIRONMENT = 'Contentful Environment'
  CONTENTFUL_CDA_ACCESS_TOKEN = 'Contentful Delivery API Key'
  CONTENTFUL_CPA_ACCESS_TOKEN = 'Contentful Preview API Key'
  UNIFORM_API_KEY='Uniform Optimize API Key'
  GATSBY_GA_UA_ID='Google Analytics ID (optional)'
